{
 "title": "New dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "db", "query": { "query": "postgresql_value" } },
   {
    "name": "entity",
    "query": "temp, blk, buffers, checkpoint, session, tup,xact"
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "active_time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "postgresql_value{job=\"postgresql\",name=\"active_time\",db=~\"$db\"}",
     "legendFormat": "{{db}}"
    }
   ]
  },
  {
   "title": "datid",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "postgresql_value{job=\"postgresql\",name=\"datid\",db=~\"$db\"}",
     "legendFormat": "{{db}}"
    }
   ]
  },
  {
   "title": "idle_in_transaction_time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "postgresql_value{job=\"postgresql\",name=\"idle_in_transaction_time\",db=~\"$db\"}",
     "legendFormat": "{{db}}"
    }
   ]
  },
  {
   "title": "max_written",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "expr": "postgresql_value{job=\"postgresql\",name=\"numbackends\",db=~\"$db\"}",
     "legendFormat": "{{db}}"
    }
   ]
  },
  {
   "title": "conflicts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "postgresql_value{job=\"postgresql\",name=\"conflicts\",db=~\"$db\"}",
     "legendFormat": "{{db}}"
    }
   ]
  },
  {
   "title": "deadlocks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 9 },
   "targets": [
    {
     "expr": "postgresql_value{job=\"postgresql\",name=\"deadlocks\",db=~\"$db\"}",
     "legendFormat": "{{db}}"
    }
   ]
  },
  {
   "title": "max_written",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "postgresql_value{job=\"postgresql\",name=\"maxwritten_clean\",db=~\"$db\"}",
     "legendFormat": "{{db}}"
    }
   ]
  },
  { "title": "temp", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "xact $db",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 18 },
   "repeat": "db",
   "targets": [
    {
     "expr": "postgresql_value{job=\"postgresql\",name=~\"^temp.*\",db=~\"$db\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "xact",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "xact $db",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 3 },
     "repeat": "db",
     "targets": [
      {
       "expr": "postgresql_value{job=\"postgresql\",name=~\"^xact.*\",db=~\"$db\"}",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  { "title": "tup", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "tup $db",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 29 },
   "repeat": "db",
   "targets": [
    {
     "expr": "postgresql_value{job=\"postgresql\",name=~\"^tup.*\",db=~\"$db\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "buffers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "buffers $db",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 39 },
   "repeat": "db",
   "targets": [
    {
     "expr": "postgresql_value{job=\"postgresql\",name=~\"^buffers_.*\",db=~\"$db\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "checkpoint",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "collapsed": true,
   "panels": [
    {
     "title": "checkpoint $db",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 6 },
     "repeat": "db",
     "targets": [
      {
       "expr": "postgresql_value{job=\"postgresql\",name=~\"^checkpoint_.*\",db=~\"$db\"}",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "blk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 },
   "collapsed": true,
   "panels": [
    {
     "title": "blk $db",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 7 },
     "repeat": "db",
     "targets": [
      {
       "expr": "postgresql_value{job=\"postgresql\",name=~\"^blk_.*\",db=~\"$db\"}",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "session",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "collapsed": true,
   "panels": [
    {
     "title": "session info",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
     "repeat": "db",
     "targets": [
      {
       "expr": "postgresql_value{job=\"postgresql\",name=~\".*session.*\",db=~\"$db\",name=~\".*_.*\"}",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  }
 ]
}