{
 "title": "DockerTelegraf",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "container_status_pid",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "docker_container_status_pid{job=\"dockertelegraf\"}",
     "legendFormat": "{{container_image}}"
    }
   ]
  },
  {
   "title": "container_cpu_usage_percent",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "docker_container_cpu_usage_percent{job=\"dockertelegraf\"}",
     "legendFormat": "{{container_image}}"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "docker_n_images{job=\"dockertelegraf\"}"
    },
    {
     "expr": "docker_n_cpus{job=\"dockertelegraf\"}"
    },
    { "expr": "docker_n_containers{}" },
    { "expr": "docker_n_containers_running{}" },
    { "expr": "docker_n_containers_stopped{}" }
   ]
  },
  {
   "title": "container_cpu_usage_total",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (container_image) (docker_container_cpu_usage_total{job=\"dockertelegraf\"})",
     "legendFormat": "{{container_image}}"
    }
   ]
  },
  {
   "title": "container_mem_usage_percent",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "docker_container_mem_usage_percent{job=\"dockertelegraf\"}",
     "legendFormat": "{{container_image}}"
    }
   ]
  }
 ]
}