{
 "title": "apache",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "scboard",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Panel Title",
     "type": "stat",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "apache_value{job=\"apache\",server=\"apache\",port=\"80\",host=\"e9a605fb81e9\",name=~\"^scboard.*\"}",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "general",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Uptime",
     "type": "stat",
     "gridPos": { "h": 7, "w": 7, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "apache_value{job=\"apache\",server=\"apache\",port=\"80\",host=\"e9a605fb81e9\",name=~\"Uptime\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Processes",
     "type": "stat",
     "gridPos": { "h": 7, "w": 5, "x": 7, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "apache_value{job=\"apache\",server=\"apache\",port=\"80\",host=\"e9a605fb81e9\",name=~\"Processes\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Stopping",
     "type": "stat",
     "gridPos": { "h": 7, "w": 5, "x": 12, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "apache_value{job=\"apache\",server=\"apache\",port=\"80\",host=\"e9a605fb81e9\",name=~\"Stopping\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Panel Title",
     "type": "stat",
     "gridPos": { "h": 7, "w": 7, "x": 17, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "apache_value{job=\"apache\",server=\"apache\",port=\"80\",host=\"e9a605fb81e9\",name=~\"^Parent.*\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Panel Title",
     "type": "stat",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "apache_value{job=\"apache\",server=\"apache\",port=\"80\",host=\"e9a605fb81e9\",name=~\".*Workers.*\"}",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "cpu data",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "apache_value{job=\"apache\",server=\"apache\",port=\"80\",host=\"e9a605fb81e9\",name=~\".*CPU.*\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Panel Title",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "apache_value{job=\"apache\",server=\"apache\",port=\"80\",host=\"e9a605fb81e9\",name=~\"^Load.*\"}",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Connection data",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Panel Title",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "apache_value{job=\"apache\",server=\"apache\",port=\"80\",host=\"e9a605fb81e9\",name=~\".*Req.*\",name!~\".*Bytes.*\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Panel Title",
     "type": "stat",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "apache_value{job=\"apache\",server=\"apache\",port=\"80\",host=\"e9a605fb81e9\",name=~\".*Total.*\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Panel Title",
     "type": "stat",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "apache_value{job=\"apache\",server=\"apache\",port=\"80\",host=\"e9a605fb81e9\",name=~\".*Bytes.*\"}",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  }
 ]
}