{
 "title": "mysql",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "command",
    "query": "commit, select, alter, insert, delete, update, create, show_create, replace, drop, show, group, grant"
   },
   {
    "name": "instance",
    "query": "row, table, user, event, db, function, index, procedure, resource_group, role, view, udf, trigger, system, server"
   },
   { "name": "errors", "query": "log, mysqlx, connection" }
  ]
 },
 "panels": [
  {
   "title": "Errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "custom errors",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "mysql_value{name=\"delayed_errors\"}"
      },
      {
       "expr": "mysql_value{name=\"com_show_errors\"}"
      }
     ]
    },
    {
     "title": "$errors errors",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
     "repeat": "errors",
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "mysql_value{name=~\".*error.*\",name=~\".*${errors}.*\"}",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": " Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "bytes sent received",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "mysql_value{name=~\"^bytes.*\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "mysql_bytes_sent",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "mysql_value{name=~\"^mysqlx_bytes_sent.*\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "mysql_bytes_sent",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "mysql_value{name=~\"^mysqlx_bytes_received.*\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "mysql_bytes_sent",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "mysql_value{name!~\"^mysqlx_bytes.*\",name!~\"^bytes.*\",name=~\".*bytes.*\"}",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Caches",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "table caches",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "mysql_value{name=~\".*cache.*\",name=~\".*table.*\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "com/threads cached",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "targets": [
      {
       "expr": "mysql_value{name=~\".*cache.*\",name=~\".*threads.*|.*com.*\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "ssl caches",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "targets": [
      {
       "expr": "mysql_value{name=~\".*cache.*\",name=~\".*ssl.*\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "binlog caches",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "targets": [
      {
       "expr": "mysql_value{name=~\".*cache.*\",name=~\".*binlog.*\"}",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Uptime",
     "type": "stat",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "mysql_value{host=\"31e7bec97da4\",server=\"mysql_container:3306\",name=~\".*uptime$.*\"}",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Connections",
     "type": "stat",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "mysql_value{host=\"31e7bec97da4\",server=\"mysql_container:3306\",name=~\".*connections$.*\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "mysqlx connections",
     "type": "stat",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "mysql_value{host=\"31e7bec97da4\",server=\"mysql_container:3306\",name=~\".*connections_.*\"}",
       "legendFormat": "{{name}}"
      },
      {
       "expr": "mysql_value{host=\"31e7bec97da4\",server=\"mysql_container:3306\",name=~\".*connections_accepted.*\"}-on (host) mysql_value{host=\"31e7bec97da4\",server=\"mysql_container:3306\",name=~\".*connections_closed.*\"}",
       "legendFormat": "running connections"
      }
     ]
    },
    {
     "title": "Panel Title",
     "type": "bargauge",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "mysql_value{host=\"31e7bec97da4\",server=\"mysql_container:3306\",name=~\".*status$.*\"}",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Operations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "number of commands $command",
     "type": "stat",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 6 },
     "repeat": "command",
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "mysql_value{host=\"31e7bec97da4\",server=\"mysql_container:3306\",name=~\"com_${command}$.*|.*com_xa_${command}$.*|.*com_${command}_${instance}$.*\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Nb of handler operations",
     "type": "stat",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 27 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "mysql_value{host=\"31e7bec97da4\",server=\"mysql_container:3306\",name=~\".*${command}.*\",name=~\".*^hand.*\"}",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  }
 ]
}